#!/bin/bash

# reading input
while [ $# -gt 0 ]; do
	if [ "$1" = "-m" ]; then	# checking fi -m flag
		shift			# shift to next arg if -m
		commit_message="$1"	# taking this arg as commit msg
		shift			# shift to next arg
	else
		file+=("$1")		# taking files that will be added to git
		shift
	fi
done

if [ -z "$commit_message" ]; then	# if the commit message doea not exist
	printf "Set a commit message: " # this step will prompt a message for you
	read commit_message		# to set the commit message
fi

git add "${file[@]}"
git commit -m "$commit_message"
git push
